[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# todo: Set Up CI Github Actions : https://gist.github.com/LukeMathWalker/5ae1107432ce283310c3e601fac915f3
[dependencies]
